# Generated by Django 4.1 on 2022-08-04 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('uljesaKojadinovic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='last name')),
                ('year_of_birth', models.DateField(blank=True, null=True, verbose_name='year of birth')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='book name')),
                ('release_year', models.DateField(blank=True, null=True, verbose_name='release year')),
                ('pages', models.IntegerField(default=0, verbose_name='pages')),
                ('ganres', models.CharField(blank=True, choices=[('Academic & Education', 'Academic & Education'), ('Art', 'Art'), ('Biography', 'Biography'), ('Business & Career', 'Business & Career'), ('Environment', 'Environment'), ('Fiction & Literature', 'Fiction & Literature'), ('Health & Fitness', 'Health & Fitness'), ('Lifestyle', 'Lifestyle'), ('Personal Growth', 'Personal Growth'), ('Politics & Laws', 'Politics & Laws'), ('Religion', 'Religion'), ('Science & Research', 'Science & Research'), ('Technology', 'Technology')], max_length=150, null=True, verbose_name='ganres')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('author', models.ManyToManyField(blank=True, related_name='author', to='uljesaKojadinovic.authorbook')),
            ],
        ),
        migrations.AddField(
            model_name='libraryuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='libraryuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='libraryuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='phone number'),
        ),
        migrations.CreateModel(
            name='BorrowBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lend_date', models.DateField(blank=True, null=True, verbose_name='lend date')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='return date')),
                ('duration', models.IntegerField(default=0, verbose_name='duration')),
                ('book', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='uljesaKojadinovic.book', verbose_name='book')),
                ('borrower', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='borrower')),
            ],
        ),
    ]
