# Generated by Django 4.1 on 2022-08-07 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uljesaKojadinovic', '0003_membershipfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='book',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='uljesaKojadinovic.book', verbose_name='book'),
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='borrower',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='borrower'),
        ),
    ]
