# Generated by Django 4.1 on 2022-08-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uljesaKojadinovic', '0007_alter_libraryuser_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryuser',
            name='active_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='libraryuser',
            name='membership_duration',
            field=models.CharField(blank=True, choices=[('one-month', 'one-month'), ('three-months', 'three-months'), ('half-year', 'half-year'), ('one-year', 'one-year')], default='one-year', max_length=150, null=True, verbose_name='membership_duration'),
        ),
        migrations.AlterField(
            model_name='libraryuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
