# Generated by Django 4.1 on 2022-08-10 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uljesaKojadinovic', '0009_borrowbook_days_left_borrowbook_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='lend_date',
            field=models.DateField(default=datetime.date.today, verbose_name='lend date'),
        ),
    ]
