# Generated by Django 4.0.7 on 2022-08-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uljesaKojadinovic', '0010_alter_borrowbook_lend_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='duration',
            field=models.IntegerField(default=15, verbose_name='duration'),
        ),
    ]
