# Generated by Django 4.0.7 on 2022-08-12 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uljesaKojadinovic', '0012_libraryuser_days_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryuser',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='start date'),
        ),
    ]
