# Generated by Django 4.0.7 on 2022-08-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uljesaKojadinovic', '0014_alter_libraryuser_options_libraryuser_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='in_stock',
            field=models.IntegerField(default=0, verbose_name='in_stock'),
        ),
    ]
