# Generated by Django 4.0.7 on 2022-11-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uljesaKojadinovic', '0015_book_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorbook',
            name='book',
            field=models.ManyToManyField(blank=True, to='uljesaKojadinovic.book'),
        ),
    ]
