# Generated by Django 4.0.7 on 2022-12-15 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uljesaKojadinovic', '0016_authorbook_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
