# Generated by Django 4.0.7 on 2022-12-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uljesaKojadinovic', '0017_remove_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorbook',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='author', to='uljesaKojadinovic.authorbook'),
        ),
    ]
